### ISSUE TITLE
Impossible installation with zend-expressive-authentication 0.5.0

### ISSUE THREAD

**Issue by coffeecore** [zendframework/zend-expressive-authentication-zendauthentication#8]
Hi,

This package can't be installed on Zend Expressive 3 :

> Problem 1
    - Installation request for zendframework/zend-expressive-authentication-zendauthentication ^0.4.0 -> satisfiable by zendframework/zend-expressive-authentication-zendauthentication[0.4.0].
    - zendframework/zend-expressive-authentication-zendauthentication 0.4.0 requires zendframework/zend-expressive-authentication ^0.4.0 -> satisfiable by zendframework/zend-expressive-authentication[0.4.0, 0.4.x-dev] but these conflict with your requirements or minimum-stability.

But, I use :

> "zendframework/zend-expressive-authentication": "^0.5.0"

So, can you update composer.json or maybe, I must not install it ?

Thanks

**Comment by weierophinney** [comment]
This package has not yet been updated to the 0.5.0 API. As such, you will need to pin to the 0.4 version of zend-expressive-authentication until we complete the update.

**Comment by coffeecore** [comment]
Do you know when you will update ?

I can wait, just curious.

**Comment by Xerkus** [comment]
Closing as no longer relevant since package uses ^1.0
